
export const partAliases = {
  "APU Exhaust": "APU Exhaust",
  "Elevator Left Wing": "Elevator Left Wing",
  "Elevator Right Wing": "Elevator Right Wing",
  "Engine 1 Casing": "Engine 1 Casing",
  "Engine 1 Cover": "Engine 1 Cover",
  "Engine 1 Exhaust Tip": "Engine 1 Exhaust Tip",
  "Engine 1 Rotor Blades": "Engine 1 Rotor Blades",
  "Engine 1 Support": "Engine 1 Support",
  "Engine 2 Casing": "Engine 2 Casing",
  "Engine 2 Cover": "Engine 2 Cover",
  "Engine 2 Exhaust Tip": "Engine 2 Exhaust Tip",
  "Engine 2 Rotor Blades": "Engine 2 Rotor Blades",
  "Engine 2 Support": "Engine 2 Support",
  "Flap A Left Wing": "Flap A Left Wing",
  "Flap A Right Wing": "Flap A Right Wing",
  "Flap B Left Wing": "Flap B Left Wing",
  "Flap B Right Wing": "Flap B Right Wing",
  "Fuselage": "Fuselage",
  "Fuselage Underbody": "Fuselage Underbody",
  "Horizontal Stabilizer Left": "Horizontal Stabilizer Left",
  "Horizontal Stabilizer Right": "Horizontal Stabilizer Right",
  "Horizontal Stabilizer Slat Left": "Horizontal Stabilizer Slat Left",
  "Horizontal Stabilizer Slat Right": "Horizontal Stabilizer Slat Right",
  "Left Gear Cover": "Left Gear Cover",
  "Left Wing": "Left Wing",
  "Nose Gear Cover Left": "Nose Gear Cover Left",
  "Nose Gear Cover Right": "Nose Gear Cover Right",
  "Nose Gear Strut": "Nose Gear Strut",
  "Nose Wheel Left": "Nose Wheel Left",
  "Nose Wheel Right": "Nose Wheel Right",
  "Nose Wheel Rim Bolt Left": "Nose Wheel Rim Bolt Left",
  "Nose Wheel Rim Bolt Right": "Nose Wheel Rim Bolt Right",
  "Nose Wheel Rim Left": "Nose Wheel Rim Left",
  "Nose Wheel Rim Right": "Nose Wheel Rim Right",
  "Pylon A Left": "Pylon A Left",
  "Pylon A Right": "Pylon A Right",
  "Pylon B Left": "Pylon B Left",
  "Pylon B Right": "Pylon B Right",
  "Pylon C Left": "Pylon C Left",
  "Pylon C Right": "Pylon C Right",
  "Right Gear Cover": "Right Gear Cover",
  "Right Wing": "Right Wing",
  "Rotor Engine 1": "Rotor Engine 1",
  "Rotor Engine 2": "Rotor Engine 2",
  "Rudder": "Rudder",
  "Strakes Engine 1": "Strakes Engine 1",
  "Strakes Engine 2": "Strakes Engine 2",
  "Tyre 1 Gear Left": "Tyre 1 Gear Left",
  "Tyre 1 Rim Gear Left": "Tyre 1 Rim Gear Left",
  "Tyre 2 Gear Left": "Tyre 2 Gear Left",
  "Tyre 3 Gear Left": "Tyre 3 Gear Left",
  "Tyre 4 Gear Left": "Tyre 4 Gear Left",
  "Vertical Stabilizer": "Vertical Stabilizer",
  "Vertical Stabilizer Front": "Vertical Stabilizer Front",
  "Windshield A Left": "Windshield A Left",
  "Windshield A Right": "Windshield A Right",
  "Windshield B Left": "Windshield B Left",
  "Windshield B Right": "Windshield B Right",
  "Wiper Left": "Wiper Left",
  "Wiper Right": "Wiper Right"
};
